import type { Metadata } from "next";
import "./global.css";
import { Theme } from "@radix-ui/themes";
import Avatar from "@/compoments/avatar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`$antialiased`}>
				<Theme>
					<nav className="navbar">
						<div className="flex space-x-4 justify-center text-xl *:my-auto">
							<Avatar
								src="https://avatars.githubusercontent.com/u/44264182?s=460&u=b59e580f37ab7e6a3979ab8a6df1f12ba6588069&v=4"
								size={32}
								className="h-8 w-8 my-auto"
							/>

							<div className="font-bold">bloodnighttw</div>
							<div className="mr-auto"></div>
						</div>
					</nav>

					{children}

					<footer className="part  border-t border-dot border-dotted">
						<div className="w-full flex flex-col md:flex-row md:space-x-4 space-y-4 md:space-y-0">
							<span className="mr-auto">
								© {new Date().getFullYear()} bloodnighttw. All
								rights reserved.
							</span>

							<span className="">
								❤️ Made with Tailwind CSS, Next.js and MkBlog.
							</span>
						</div>
					</footer>
				</Theme>
			</body>
		</html>
	);
}
